### ISSUE TITLE
improve documentation for forge configuration

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/forge-docs#123]
这个需求提出方式上汽集团的工程师，不过我们的配置文档确实比较简陋。文档需要回答的几个关键问题：
- 配置文件的位置
- 每个配置项都可以取什么值，配置项之间的依赖关系？
- 哪些是链的配置？哪些是节点的配置？
- 哪些配置项可以修改？哪些不可以修改？

**Comment by rileyshu53** [comment]
done
