### ISSUE TITLE
general introduction documentation to asset

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/forge-docs#132]
- What are assets?
- Use cases for assets?
- Asset related transactions
- Common concerns about assets? how to make them secure?
- ABT Wallet support for assets: Asset Protocol?

**Comment by rileyshu53** [comment]
@wangshijun  Could you take a look and suggest some changes if necessary https://github.com/ArcBlock/forge-docs/pull/135
@PaperHS  Could you take a look and see if we can add asset protocol description in the end?
