### ISSUE TITLE
command is not found.

### ISSUE THREAD

**Issue by cerebrowang** [ArcBlock/forge-docs#141]
at MacOS Catalina.
Follow the guide.
% xcode-select --install
%  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
% brew install automake libtool pkg-config libffi gmp openssl
% brew install node
% node -v //v13.6.0
% npm -v //6.13.4
% npm install -g @arcblock/forge-cli
% forge -h  //zsh: command not found: forge
??? what's happened?

**Comment by polunzh** [comment]
This may be caused by your local npm environment, you can try to solve it through the guide from StackOverflow:
https://superuser.com/a/1081802/1108068

**Comment by cerebrowang** [comment]
I have the world, then no-result.

Then i Add export PATH=/Users/cerebro/usr/lib/node_modules/@arcblock/forge-cli/bin/:/bin:/usr/bin:/usr/local/bin:$PATH

It's OK. 
Anyway, Thanks you.
